# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ed162ca200c5227f5cc36d7a26ee6693bc35047d160087bf80efeab1050a1bf7249ec50134f2990317da648606e3c119e65313a90631bd06fd4c4b2893cf5ce

test:
  secret_key_base: cfcd8b1bc8443f4fc259b74deaa91e224e77d1e80015554607f6e086eb0070246d55af59e86b6b19a2af123a0da8638c6ec5d7ce752663964cf3a612af2b7004

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
